## roles/update/tasks/Archlinux.yml
## Role main file
# vim:ft=ansible:
---
- name: "Unlock pacman ... use with caution! :p"
  file:
    path: /var/lib/pacman/db.lck
    state: absent

- name: Pacman.conf
  template:
    src: pacman.conf.j2
    dest: /etc/pacman.conf

- name: Proper mirrorlist
  template:
    src: mirrorlist.j2
    dest: /etc/pacman.d/mirrorlist

- name: Update all non-AUR packages (Pacman-based distros)
  pacman:
    update_cache: yes
    upgrade: yes

- name: Update AUR-packages with yaourt
  command: yaourt -Syu --noconfirm
  become: yes
  become_user: '{{ as_user }}'
  when: "'yaourt' in aur_app"

- name: Update AUR-packages with pacaur
  command: pacaur -Syu --noconfirm --needed --noprogressbar
  become: yes
  become_user: '{{ as_user }}'
  when: "'pacaur' in aur_app"

...
