## roles/update/tasks/main.yml
## Role main file
# vim:ft=ansible:
---
## Launch apropriate protocol in regards of package manager.
- include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: update
...
